### LIST QUESTIONS
GET http://localhost:3000/api/questionlist


### GET QUESTION BY ID
GET http://localhost:3000/api/question/1


### POST QUESTION
POST http://localhost:3000/api/question
Content-Type: application/json
Cookie: authToken=

{
    "question": {
        "title": "", 
        "details": ""
    }
}


### DELETE QUESTION
DELETE http://localhost:3000/api/question/1
Content-Type: application/json
Cookie: authToken=


### UPDATE QUESTION
PATCH  http://localhost:3000/api/question/1
Content-Type: application/json
Cookie: authToken=
{
    "question": {
        "title": "",
        "details": ""
    }
}


### UPVOTE QUESTION
POST http://localhost:3000/api/upvote/1
Content-Type: application/json
Cookie: authToken=


### SET QUESTION TO SOLVED
POST http://localhost:3000/api/solve/1
Cookie: authToken=


### POST ANSWER
POST http://localhost:3000/api/postanswer/1
Content-Type: application/json
Cookie: authToken=

{
    "answer": {
        "answer": ""
    }
}


### GET ANSWERS BY QUESTION
GET http://localhost:3000/api/answers/1
Cookie: authToken=