###
POST http://localhost:3001/api/auth_v1/register
Content-Type: application/json

{
    "username": "",
    "password": ""
}


###
POST http://localhost:3001/api/auth_v1/login
Content-Type: application/json

{
    "username": "",
    "password": ""
}


###
POST http://localhost:3001/api/auth_v1/logout


###
POST http://localhost:3001/api/auth_v1/authenticate
Content-Type: application/json

{
    "authToken": ""
}